Areas/Admin/Controllers/AdmStatisticsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tennis.Interfaces;
using Tennis.Models;

namespace Tennis.Areas.Admin.Controllers;

[Area("Admin")]
public class AdmStatisticsController : Controller
{
	private static int xx, yy, zz;
	private readonly ICategoryRepository _categoryRepository;
	private readonly ICustomerRepository _customerRepository;
	private readonly IOrderDetailRepository _orderDetailRepository;
	private readonly IOrderRepository _orderRepository;
	private readonly IProductRepository _productRepository;

	public AdmStatisticsController(IProductRepository productRepository, IOrderDetailRepository orderDetailRepository,
		IOrderRepository orderRepository, ICustomerRepository customerRepository,
		ICategoryRepository categoryRepository)
	{
		_productRepository = productRepository;
		_orderDetailRepository = orderDetailRepository;
		_orderRepository = orderRepository;
		_customerRepository = customerRepository;
		_categoryRepository = categoryRepository;
	}

	public IActionResult Index()
	{
		return View();
	}

	private string GetRandomColour()
	{
		var random = new Random();
		xx = (xx + DateTime.Now.Millisecond + DateTime.Now.Second + random.Next(24)) % 256;
		yy = (yy + DateTime.Now.Millisecond + DateTime.Now.Second + DateTime.Now.Hour) % 256;
		zz = (zz + DateTime.Now.Millisecond + DateTime.Now.Second + DateTime.Now.Minute) % 256;
		return "rgb(" + xx + "," + yy + "," + zz + ")";
	}

	//Lấy ra danh sách Customer : Số đơn hàng
	public IActionResult StaticOrdersByUsers(int option = 0)
	{
		var time = new Period(option);
		return View(_customerRepository.GetTopOrder(time.startDate, time.endDate).OrderByDescending(x => x.Value));
	}

	//Lấy ra danh sách Customer : Tổng số tiền đã chi trong khoảng thời gian gần đây
	public IActionResult StaticRevenueByUsers(int option = 0)
	{
		var time = new Period(option);
		return View(_customerRepository.GetTopRevenue(time.startDate, time.endDate).OrderByDescending(x => x.Value));
	}

	//Trả về khoảng thời gian tương ứng với option
	private string TimeOption(int option)
	{
		switch (option)
		{
			case 1:
				return "tháng này";
			case 2:
				return "năm nay";
			case 3:
				return "từ trước đến nay";
			default:
				return "hôm nay";
		}
	}

	//Truyền dữ liệu cho bar chart
	//bar là data set up cho chart, data là data đã được lấy ra từ cơ sở dữ liệu
	private void SetupBarChart(Bar bar, Table[] data)
	{
		var amount = data.Count(); // số lượng cột của chart

		for (var i = 0; i < amount; i++)
		{
			bar.data.labels[i] = data[i].Key; //tên các cột 
			bar.data.datasets[0].backgroundColor[i] = GetRandomColour(); //màu ngẫu nhiên cho cột
			bar.data.datasets[0].borderColor[i] = GetRandomColour(); //màu viền cho cột
			bar.data.datasets[0].data[i] = data[i].Value; //giá trị của cột
			//  bar.data.datasets[0].label = data[i].Key;
		}
	}

	//Truyền dữ liệu cho line chart
	//line là data set up cho Line chart
	private void SetupLineChart(Line line, Table[] data)
	{
		for (var i = 1; i <= 12; i++)
		{
			line.data.labels[i - 1] = data[i].Key;
			line.data.datasets[0].borderColor = GetRandomColour();
			line.data.datasets[0].data[i - 1] = data[i].Value;
		}
	}

	private void SetupPieChart(Pie pie, Table[] data)
	{
		var amount = data.Count();
		for (var i = 0; i < amount; i++)
		{
			pie.data.labels[i] = data[i].Key;
			pie.data.datasets[0].backgroundColor[i] = GetRandomColour();
			pie.data.datasets[0].data[i] = data[i].Value;
		}
	}

	//Thống kê số lượng sản phẩm bán ra trong khoảng thời gian option bằng bar chart 
	//option default là trong ngày
	public IActionResult StaticProductAmount(int option = 0)
	{
		//set up giá trị default cho select list
		ViewData["option"] = option;
		ViewData["optionName"] = TimeOption(option);

		//Lấy khoảng thời gian tương ứng với option
		var time = new Period(option);

		//Lấy data từ cơ sở dữ liệu
		var data = _productRepository
			.GetProductWithAmount(time.startDate, time.endDate)
			.OrderByDescending(x => x.Value).ToArray();
		var amount = data.Count(); // số lượng cột của chart

		//Tạo chart mới với số cột amount
		var productAmount = new Bar(amount); //Setup các thông số cho chart
		SetupBarChart(productAmount, data);
		productAmount.options.plugins.title.text =
			"Số lượng sản phẩm bán được trong " + TimeOption(option); //Đặt tên cho chart
		//productAmount.data.labels[0] = "Doanh số";
		return View(productAmount);
	}

	//Thống kê doanh thu từng sản phẩm bán ra trong khoảng thời gian option bằng bar chart 
	//option default là trong ngày
	public IActionResult StaticProductRevenue(int option = 0)
	{
		//set up giá trị default cho select list
		ViewData["option"] = option;
		ViewData["optionName"] = TimeOption(option);

		//Lấy khoảng thời gian tương ứng với option
		var time = new Period(option);

		//Lấy data từ cơ sở dữ liệu
		var data = _productRepository.GetProductWithRevenue(time.startDate, time.endDate)
			.OrderByDescending(x => x.Value).ToArray();
		var amount = data.Count(); // số lượng cột của chart

		//Tạo chart mới với số cột amount
		var productRevenue = new Bar(amount);
		SetupBarChart(productRevenue, data); //Setup các thông số cho chart
		productRevenue.options.plugins.title.text =
			"Doanh thu sản phẩm bán được trong " + TimeOption(option); // Đặt tên cho chart
		// productRevenue.data.labels[0] = "Doanh thu";
		return View(productRevenue);
	}

	//Thống kê số lượng bán được/ doanh thu của sản phẩm product theo tháng trong năm nay bằng line chart
	//option default là số lượng bán được
	public IActionResult StaticProduct(int product = 3, int option = 0)
	{
		var text = option == 0 ? "Doanh số" : "Doanh thu";
		ViewData["option"] = option;
		ViewData["optionName"] = text;
		var listProduct = _productRepository.GetListProduct();
		ViewData["listProduct"] = new SelectList(listProduct, "Value", "Key");
		Table[] data;
		switch (option)
		{
			case 1:
				data = _productRepository.GetProductRevenueInYear(product);
				break;
			default:
				data = _productRepository.GetProductAmountInYear(product);
				break;
		}

		var productLine = new Line(12);
		productLine.data.datasets = new Line.Data.Dataset[1];
		productLine.data.datasets[0] = new Line.Data.Dataset(12);
		SetupLineChart(productLine, data);
		productLine.options.plugins.title.text = text;
		productLine.data.datasets[0].label = text;
		return View(productLine);
	}

	//Thống kê cơ cấu doanh thu theo năm {option} bằng pie chart
	//option default là năm nay
	public IActionResult RevenueStructure(int? option)
	{
		if (option == null)
			option = DateTime.Now.Year;
		ViewData["option"] = option;
		var data = _categoryRepository.GetRevenueStructure((int)option);
		var amount = data.Count();
		var revenueStructure = new Pie(amount);
		revenueStructure.options.plugins.title.text = "Cơ cấu doanh thu năm " + option;
		SetupPieChart(revenueStructure, data);
		return View(revenueStructure);
	}
}

Areas/Admin/Views/AdmStatistics/Index.cshtml
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="pagetitle">
	<h1>Dashboard</h1>
	<nav>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a asp-action="Index" asp-controller="Home">Trang chủ</a>
			</li>
			<li class="breadcrumb-item active">Báo cáo và phân tích khinh doanh</li>
		</ol>
	</nav>
</div><!-- End Page Title -->

<section class="section dashboard">
<div class="row">

<!-- Left side columns -->
<div class="col-lg-8">
	<div class="row">
		<!-- Reports -->
		<div class="col-12">
			<div class="card">

				<div class="filter">
					<a class="icon" href="#" data-bs-toggle="dropdown">
						<i class="bi bi-three-dots"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
						<li class="dropdown-header text-start">
							<h6>Lọc</h6>
						</li>

						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductRevenue"
							   asp-route-option="0"
							   data-ajax="true" data-ajax-update="#Static-Product-Revenue">
								Trong ngày
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductRevenue"
							   asp-route-option="1"
							   data-ajax="true" data-ajax-update="#Static-Product-Revenue">
								Trong tháng
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductRevenue"
							   asp-route-option="2"
							   data-ajax="true" data-ajax-update="#Static-Product-Revenue">
								Trong năm
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductRevenue"
							   asp-route-option="3"
							   data-ajax="true" data-ajax-update="#Static-Product-Revenue">
								Từ trước đến nay
							</a>
						</li>
					</ul>
				</div>


				<div class="card-body">
					<h5 class="card-title">Thống kê doanh thu từng sản phẩm<span>/@ViewData["optionName"]</span></h5>
					<form asp-action="StaticProductRevenue" method="get">
						<select name="option">
							<option value=@ViewData["option"]>@ViewData["optionName"]</option>
							<option value="0">Trong ngày</option>
							<option value="1">Trong tháng</option>
							<option value="2">Trong năm</option>
							<option value="3">Từ trước đến nay</option>
						</select>
						<input value="Submit" type="submit"/>
					</form>
					<div id="Static-Product-Revenue">
						@await Component.InvokeAsync("StaticProductRevenueComponent")
					</div>
				</div>

			</div>
		</div><!-- End Reports -->
		<!-- Recent Sales -->
		<div class="col-12">
			<div class="card recent-sales overflow-auto">

				<div class="filter">
					<a class="icon" href="#" data-bs-toggle="dropdown">
						<i class="bi bi-three-dots"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
						<li class="dropdown-header text-start">
							<h6>Lọc</h6>
						</li>

						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductAmount"
							   asp-route-option="0"
							   data-ajax="true" data-ajax-update="#Static-Product-Amount">
								Trong ngày
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductAmount"
							   asp-route-option="1"
							   data-ajax="true" data-ajax-update="#Static-Product-Amount">
								Trong tháng
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductAmount"
							   asp-route-option="2"
							   data-ajax="true" data-ajax-update="#Static-Product-Amount">
								Trong năm
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProductAmount"
							   asp-route-option="3"
							   data-ajax="true" data-ajax-update="#Static-Product-Amount">
								Từ trước đến nay
							</a>
						</li>
					</ul>
				</div>

				<div class="card-body">
					<h5 class="card-title">Thống kê số lượng từng sản phẩm<span>| @ViewData["optionName"]</span></h5>
					<form asp-action="StaticProductAmount" method="get">
						<select name="option">
							<option value=@ViewData["option"]>@ViewData["optionName"]</option>
							<option value="0">Trong ngày</option>
							<option value="1">Trong tháng</option>
							<option value="2">Trong năm</option>
							<option value="3">Từ trước đến nay</option>
						</select>
						<input value="Submit" type="submit"/>
					</form>
					<div id="Static-Product-Amount">
						@await Component.InvokeAsync("StaticProductAmountComponent")
					</div>

				</div>

			</div>
		</div><!-- End Recent Sales -->
		<!-- Top Selling -->
		<div class="col-12">
			<div class="card top-selling overflow-auto">

				<div class="filter">
					<a class="icon" href="#" data-bs-toggle="dropdown">
						<i class="bi bi-three-dots"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
						<li class="dropdown-header text-start">
							<h6>Lọc</h6>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProduct"
							   asp-route-option="0"
							   data-ajax="true" data-ajax-update="#Static-Product-Amount">
								Doanh số
							</a>
						</li>
						<li>
							<a class="dropdown-item" asp-controller="AdmStatistics"
							   asp-action="StaticProduct"
							   asp-route-option="1"
							   data-ajax="true" data-ajax-update="#Static-Product-Amount">
								Doanh thu
							</a>
						</li>
					</ul>
				</div>

				<div class="card-body pb-0">
					<h5 class="card-title">Phân tích sản phẩm <span>| @ViewData["optionName"]</span></h5>

					<form asp-action="StaticProduct" method="get">
						<select name="option">
							<option selected value=@ViewData["option"]>@ViewData["optionName"]</option>
							<option value="0">Doanh số</option>
							<option value="1">Doanh thu</option>
						</select>
						<select name="product" asp-items="@ViewData["listProduct"] as SelectList"></select>
						<input type="submit" value="Submit"/>
					</form>
					<div id="Static-Product">
						@await Component.InvokeAsync("StaticProductComponent")
					</div>
				</div>
			</div>
		</div><!-- End Top Selling -->


	</div>
</div><!-- End Left side columns -->
<!-- Right side columns -->
<div class="col-lg-4">

	<!-- Top Selling -->
	<div class="card top-selling overflow-auto">

		<div class="filter">
			<a class="icon" href="#" data-bs-toggle="dropdown">
				<i class="bi bi-three-dots"></i>
			</a>
			<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
				<li class="dropdown-header text-start">
					<h6>Lọc</h6>
				</li>
				<li>
					<a class="dropdown-item" asp-controller="AdmStatistics"
					   asp-action="RevenueStructure"
					   asp-route-option="0"
					   data-ajax="true" data-ajax-update="#Revenue-Structure">
						Trong năm
					</a>
				</li>
				<li>
					<a class="dropdown-item" asp-controller="AdmStatistics"
					   asp-action="RevenueStructure"
					   asp-route-option="1"
					   data-ajax="true" data-ajax-update="#Revenue-Structure">
						Trong tháng
					</a>
				</li>
				<li>
					<a class="dropdown-item" asp-controller="AdmStatistics"
					   asp-action="RevenueStructure"
					   asp-route-option="1"
					   data-ajax="true" data-ajax-update="#Revenue-Structure">
						Trong ngày
					</a>
				</li>
			</ul>
		</div>

		<div class="card-body pb-0">
			<h5 class="card-title">Cơ cấu doanh thu <span>| Today</span></h5>
			<form asp-action="RevenueStructure" method="get">
				<select name="option">
					<option value=@ViewData["option"]>@ViewData["option"]</option>
					<option value="0">2026</option>
					<option value="1">2025</option>
					<option value="2">2024</option>
				</select>
				<input value="Submit" type="submit"/>
			</form>
			<div id="Revenue-Structure">
				@await Component.InvokeAsync("RevenueStructureComponent")
			</div>

		</div>

	</div>
	<!-- Budget Report -->
	<div class="card">
		<div class="filter">
			<a class="icon" href="#" data-bs-toggle="dropdown">
				<i class="bi bi-three-dots"></i>
			</a>
			<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
				<li class="dropdown-header text-start">
					<h6>Filter</h6>
				</li>

				<li>
					<a class="dropdown-item" href="#">Today</a>
				</li>
				<li>
					<a class="dropdown-item" href="#">This Month</a>
				</li>
				<li>
					<a class="dropdown-item" href="#">This Year</a>
				</li>
			</ul>
		</div>

		<div class="card-body pb-0">
			<h5 class="card-title">Budget Report <span>| This Month</span></h5>

			<div id="budgetChart" style="min-height: 400px;" class="echart"></div>

		</div>
	</div><!-- End Budget Report -->
	<!-- Website Traffic -->
	<div class="card">
		<div class="filter">
			<a class="icon" href="#" data-bs-toggle="dropdown">
				<i class="bi bi-three-dots"></i>
			</a>
			<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
				<li class="dropdown-header text-start">
					<h6>Filter</h6>
				</li>

				<li>
					<a class="dropdown-item" href="#">Today</a>
				</li>
				<li>
					<a class="dropdown-item" href="#">This Month</a>
				</li>
				<li>
					<a class="dropdown-item" href="#">This Year</a>
				</li>
			</ul>
		</div>

		<div class="card-body pb-0">
			<h5 class="card-title">Website Traffic <span>| Today</span></h5>

			<div id="trafficChart" style="min-height: 400px;" class="echart"></div>

		</div>
	</div><!-- End Website Traffic -->
	<!-- News & Updates Traffic -->
	<div class="card">
		<div class="filter">
			<a class="icon" href="#" data-bs-toggle="dropdown">
				<i class="bi bi-three-dots"></i>
			</a>
			<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
				<li class="dropdown-header text-start">
					<h6>Filter</h6>
				</li>

				<li>
					<a class="dropdown-item" href="#">Today</a>
				</li>
				<li>
					<a class="dropdown-item" href="#">This Month</a>
				</li>
				<li>
					<a class="dropdown-item" href="#">This Year</a>
				</li>
			</ul>
		</div>

		<div class="card-body pb-0">
			<h5 class="card-title">News &amp; Updates <span>| Today</span></h5>

		</div>
	</div><!-- End News & Updates -->

</div><!-- End Right side columns -->

</div>
</section>

Areas/Admin/Views/AdmStatistics/RevenueStructure.cshtml
@using Newtonsoft.Json
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="pagetitle">
	<h1>Dashboard</h1>
	<nav>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a asp-action="Index" asp-controller="Home">Trang chủ</a>
			</li>
			<li class="breadcrumb-item active">Báo cáo và phân tích khinh doanh</li>
		</ol>
	</nav>
</div><!-- End Page Title -->


<section class="section dashboard">
	<div class="row">

		<!-- Left side columns -->
		<div class="col-lg-8">
			<div class="row">

				<div class="col-12">
					<div class="card top-selling overflow-auto">

						<div class="filter">
							<a class="icon" data-bs-toggle="dropdown">
								<i class="bi bi-three-dots"></i>
							</a>
							<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
								<li class="dropdown-header text-start">
									<h6>Lọc</h6>
								</li>
								<li>
									<a class="dropdown-item" asp-controller="AdmStatistics"
									   asp-action="RevenueStructure"
									   asp-route-option="2026"
									   data-ajax="true" data-ajax-update="#newchart">
										2022
									</a>
								</li>

								<li>
									<a class="dropdown-item" asp-controller="AdmStatistics"
									   asp-action="RevenueStructure"
									   asp-route-option="2025"
									   data-ajax="true" data-ajax-update="#newchart">
										2021
									</a>
								</li>
								<li>
									<a class="dropdown-item" asp-controller="AdmStatistics"
									   asp-action="RevenueStructure"
									   asp-route-option="2024"
									   data-ajax="true" data-ajax-update="#Static-Product-Amount">
										2020
									</a>
								</li>
							</ul>
						</div>

						<div class="card-body pb-0">
							<h5 class="card-title">Phân tích sản phẩm <span>|</span></h5>
							<form asp-action="RevenueStructure" method="get">
								<div class="col-md-2">

									<select name="option" class="form-select">
										<option value=@ViewData["option"]>@ViewData["option"]</option>
										<option value="2026">2026</option>
										<option value="2025">2025</option>
										<option value="2024">2024</option>
									</select>
								</div>
								<div class="col-md-2">
									<input value="Thống kê" type="submit" class="btn btn-primary"/>

								</div>
							</form>
							<canvas id="newchart"></canvas>

							<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
							<script src="~/js/jquery.js"></script>
							<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
							<script type="text/javascript">
                                $(function () {


                                    var ctx = document.getElementById('newchart').getContext('2d');
                                    var model = @Html.Raw(JsonConvert.SerializeObject(Model) as string);
                                    console.log(model)
                                    var doanhthunam = new Chart(ctx, model)
                                });


                            </script>

						</div>
					</div>
				</div><!-- End Top Selling -->
			</div>
		</div><!-- End Left side columns -->

	</div>
</section>

Areas/Admin/Views/AdmStatistics/StaticProduct.cshtml
@using Newtonsoft.Json
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="pagetitle">
	<h1>Dashboard</h1>
	<nav>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a asp-action="Index" asp-controller="Home">Trang chủ</a>
			</li>
			<li class="breadcrumb-item active">Báo cáo và phân tích khinh doanh</li>
		</ol>
	</nav>
</div><!-- End Page Title -->


<section class="section dashboard">
	<div class="row">

		<!-- Left side columns -->
		<div class="col-lg-8">
			<div class="row">

				<div class="col-12">
					<div class="card top-selling overflow-auto">

						<div class="filter">
							<a class="icon" data-bs-toggle="dropdown">
								<i class="bi bi-three-dots"></i>
							</a>
							<ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow">
								<li class="dropdown-header text-start">
									<h6>Lọc</h6>
								</li>
								<li>
									<a class="dropdown-item" asp-controller="AdmStatistics"
									   asp-action="RevenueStructure"
									   asp-route-option="2026"
									   data-ajax="true" data-ajax-update="#newchart">
										2022
									</a>
								</li>

								<li>
									<a class="dropdown-item" asp-controller="AdmStatistics"
									   asp-action="RevenueStructure"
									   asp-route-option="2025"
									   data-ajax="true" data-ajax-update="#newchart">
										2021
									</a>
								</li>
								<li>
									<a class="dropdown-item" asp-controller="AdmStatistics"
									   asp-action="RevenueStructure"
									   asp-route-option="2024"
									   data-ajax="true" data-ajax-update="#Static-Product-Amount">
										2020
									</a>
								</li>
							</ul>
						</div>

						<div class="card-body pb-0">
							<h5 class="card-title">Phân tích sản phẩm <span>|</span></h5>
							<form asp-action="StaticProduct" method="get">
								<div class="col-md-4">
									<select name="option" class="form-select">
										<option selected value=@ViewData["option"]>@ViewData["optionName"]</option>
										<option value="0">Doanh số</option>
										<option value="1">Doanh thu</option>
									</select>
									<select class="form-select" name="product" asp-items="@ViewData["listProduct"] as SelectList"></select>
								</div>
								<input type="submit" value="Thống kê" class="btn btn-primary"/>
							</form>
							<canvas id="newchart"></canvas>
							<!--<div class="row">-->
							<!-- Pie Chart -->
							<!--<div class="col-xl-6 col-lg-7">
							<div class="card shadow mb-4">-->
							<!-- Card Header - Dropdown -->
							<!--<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
								<h6 class="m-0 font-weight-bold text-primary">
									Doanh thu gói theo nă
								</h6>
							</div>-->
							<!-- Card Body -->
							<!--<div class="card-body">

							</div>
							</div>
							</div>
							</div>-->
							<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
							<script src="~/js/jquery.js"></script>
							<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
							<script type="text/javascript">
                                $(function () {


                                    var ctx = document.getElementById('newchart').getContext('2d');
                                    var model = @Html.Raw(JsonConvert.SerializeObject(Model) as string);
                                    console.log(model)
                                    var hi = new Chart(ctx, model)
                                });


                            </script>

						</div>
					</div>
				</div><!-- End Top Selling -->
			</div>
		</div><!-- End Left side columns -->

	</div>
</section>